[project]
name = "shape-description-language"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bitstring>=4.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
